main-ignore: &main-ignore
  filters:
    branches:
      ignore: main

main-only: &main-only
  filters:
    branches:
      only: main


version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.2
  aws-ecs: circleci/aws-ecs@1.4.0
jobs:
  check_pull_request:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run:
          name: Build
          command: ./gradlew clean build
      - store_test_results:
          path: build/test-results/test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
  build_artifact:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run:
          name: Run tests
          command: ./gradlew clean test
      - run:
          name: Generate code coverage report
          command:
            ./gradlew jacocoTestReport
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/jacocoHtml
      - run:
          name: Build artifact
          command: ./gradlew build -x test
      - store_artifacts:
          path: build/libs
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
  create_tag:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Git create tag
          command: git tag -a "0.<< pipeline.number >>"
      - run:
          name: Git push tag
          command: git push --tag

workflows:
  version: 2
  pull_request_check:
    jobs:
      - check_pull_request:
          <<: *main-ignore
  dev_deployment:
    jobs:
      - build_artifact:
          <<: *main-only
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          repo: test-circle-ci
          tag: "0.<< pipeline.number >>"
          requires:
            - build_artifact
          <<: *main-only